plugins {
    id 'groovy'

    id 'org.springframework.boot' version '3.5.4'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.example'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {

    // Groovy
    implementation 'org.apache.groovy:groovy:4.0.27'

    // Spring Boot Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // JUnit 5 + Spring Boot testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // JUnit Platform
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}